// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: proto/service_order.proto

/* eslint-disable */

export const protobufPackage = "service_order";

export interface ErrorCode {
  code: number;
  message: string;
}

export interface BuyReq {
  token: string;
  bookName: string;
}

export interface BuyResp {
  errorCode: ErrorCode | undefined;
  message: string;
}

export interface OrderService {
  Buy(request: BuyReq): Promise<BuyResp>;
}
