// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: proto/service_account.proto

/* eslint-disable */

export const protobufPackage = 'service_account';

export interface ErrorCode {
  code: number;
  message: string;
}

export interface SignInReq {
  username: string;
  password: string;
}

export interface SignInResp {
  errorCode: ErrorCode | undefined;
  token: string;
}

export interface VerifyTokenReq {
  token: string;
}

export interface VerifyTokenResp {
  errorCode: ErrorCode | undefined;
}

export interface AccountService {
  SignIn(request: SignInReq): Promise<SignInResp>;
  VerifyToken(request: VerifyTokenReq): Promise<VerifyTokenResp>;
}
